// ignore_for_file: file_names

import 'package:get/get.dart';

class Lan extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "continue": "استمرار",
          "send": "ارسال",
          "dnthaveacc": "حساب جديد",
          "email": "البريد الاكتروني",
          "pass": "كلمه المرور",
          "cat": "اداره الاقسام",
          "male": "ذكر",
          "female": "انثى",
          "mobile": "الهاتف",
          "save": "حفظ",
          "again": "طلب مره اخرى",
          "compa": "اداره المقارنات",
          "storname": "اسم المتجر",
          "itemname": "اسم السلعه",
          "price": "السعر",
          "accept": "تم الانتهاء",
          "done": "منتهي",
          "reject": "مرفوض",
          "pending": "قيد الانتظار",
          "refuse": "رفض",
          "order": "طلب",
          "username": "اسم المستخدم",
          "name": "الاسم",
          "add": "اضافه",
          "groups": "المجموعات",
          "grname": 'اسم المجموعه',
          "ordername": "تفاصيل الطلب",
          "note": "ملاحظات ..",
          "addorder": "اضف طلب",
          "addperson": "اضافه صديق",
          "myorder": "طلباتي",
          "ordertome": "مطلوب مني",
          "addfamily": "اضف الى الاصدقاء",
          "home": "الرئيسيه",
          "allrequests": "طلباتي",
          "allrequired": "مطلوب مني",
          "chat": "دردشه",
          "settings": "اعدادت",
          "profile": "الصفحه الشخصيه",
          "lang": "اللغه",
          "edit": "تعديل",
          "photo": "صوره",
          "cancel": "الغاء",
          "logout": "تسجيل الخروج",
          "acceptt": "جاري التنفيذ",
          "saveasdraft": "حفظ ك مسوده",
          "drafts": "مسودات",
          "addcat": "اضافه قسم",
          "guest": "الدخول ك ضيف",
          "shoulsignin": 'لست مستخدم يرجى تسجيل الدخول',
          "signin": "تسجيل دخول",
          "signup": "التسجيل",
          "addmobile": " برجاء ادخال رقم الهاتف لتسجيل الدخول",
          "ok": "حسنا",
          "deleteacc": "حذف الحساب"
        },
        "en": {
          "continue": "continue",
          "send": "send",
          "dnthaveacc": "Sign up",
          "email": "Email",
          "pass": "Password",
          "cat": "categories",
          "male": "Male",
          "female": "Female",
          "mobile": "Mobile",
          "save": "Save",
          "again": "Order again",
          "compa": "Comparisons",
          "itemname": "Item name",
          "price": "Price",
          "accept": "Been completed",
          "done": "Finished",
          "reject": "unacceptable",
          "pending": "pending",
          "refuse": "reject",
          "order": "Order",
          "username": "User Name",
          "name": "Name",
          "add": "Add",
          "groups": "Groups",
          "grname": 'Group name',
          "ordername": "Order details",
          "note": "Notes ..",
          "addorder": "Add Order",
          "myorder": "My Orders",
          "ordertome": "Required",
          "addfamily": "Add to my family",
          "home": "Home",
          "allrequests": "All Orders",
          "allrequired": "All Required",
          "chat": "Chat",
          "settings": "Settings",
          "profile": "Profile",
          "lang": "Language",
          "photo": "Photo",
          "cancel": "Cancel",
          "logout": "Sign Out",
          "guest": "Continue as guest",
          "shoulsignin": "You are no a register user please login",
          "signin": "Sign In",
          "addmobile": "Enter Mobile to login",
          "ok": 'Ok',
          "deleteacc": "Delete Account"
        }
      };
}
